### ISSUE TITLE
Subdirectory upload -> is it possible to upload to WinAppDataLocal

### ISSUE THREAD

**Issue by Wurrkop** [rhsCZ/steamcloud#2]
Hello!

Im having issues with a game that saves files in WinAppDataLocal:
https://i.imgur.com/3MFhFXq.png
<html>
<body>

WinAppDataLocal | Saber/Space Marine 2/storage/steam/user/USERID/Main/config/loadouts.cfg
-- | --

</body>
</html>

Is it possible to upload like that?

Directories/Files uploaded end up like this:
https://i.imgur.com/oKe8M8V.png
And end up syncing to:
\Steam\userdata\USERID\2183900\remote
Instead of in:
AppData\Local\Saber\Space Marine 2\storage\steam\user\USERID\Main\config

**Comment by rhsCZ** [comment]
Hi, sorry about late response. What had you typed in directory selection dialog? Can you provide image of what files look like in steamcloud app?
I have to figure out if it's even possible (probably yes) and how to achieve it.

**Comment by Wurrkop** [comment]
Hey, thanks for responding and no worries about the delay, im thankful you feel like looking into this.

Currently there isnt anything showing in the steamcloud app, when i connect the file listing section remains unpopulated, probably due to me removing the locally wrongly placed files while i had i the app running, then closing the app to force a sync in order to clean up the mess.

Im not sure what is the expected behaviour, am i supposed to be seeing the same stuff in the app as on https://store.steampowered.com/account/remotestorageapp/?appid=2183900 or just the files ive manually uploaded?
The latter was the case when i had uploaded files, those i could see, the others (synced/uploaded automagically by the actual game) i could not.

I cant actually remember how i did the upload, either it was by using the pick folder option provided in the app or by text string as you showed here: https://github.com/GMMan/SteamCloudFileManagerLite/pull/10

This whole situation is odd to me because my understanding is that files present in the sync folder would get kicked into the cloud on game/app exit.

This game somehow retains (at least) the loadout and campaign progress files even when starting the game or steamcloud app, then switch files, with the game/steamcloud app still running, then close either. Steam shows the cloud updating but the problem remains.

On another note, hitting disconnect in the app doesnt actually start the sync, i have to fully exit the app for the sync to happen as steam reports the game as still running until i do, my guess is that this is unrelated to my folders issue tho so might be a different topic.

**Comment by rhsCZ** [comment]
Thank you for additional info. I will look into it. I am not sure how steam cloud sync works, but i think that on exit it maybe only push any changes made to files by Steam API. I don't think putting files somewhere would kick them to cloud without involving Steam API.

On that disconnect, i know about this issue. I have tried to fix it but without any luck. Problem is that once is app/game initialized it won't exit game even if i invoke SteamAPI_Shutdown() function. Probably steam_api.dll/steam_api64.dll is remain loaded by app causing steam to think, that game is still running or steam probably gets PID (process ID) and wait's until process with that PID finishes execution. I could try unloading DLL in runtime. I will try it some another time. separating app into 2 processes seems too much complication for this. If unloading DLL will not help, than i will let it be as is.

**Comment by rhsCZ** [comment]
So i looked into it (It's called Steam Auto-Cloud) and i found out it is not accessible by written code via Steam API. It is something baked into steam directly and set by developers for some games.
Here is some info about it if you are interested [https://partner.steamgames.com/doc/features/cloud#steam_auto-cloud](https://partner.steamgames.com/doc/features/cloud#steam_auto-cloud)
Only way to upload/delete files is:
1. launch game or init game by steamcloud
2. delete/edit/add files in %USERPROFILE%\AppData\Local\......... (folowed by path specific for game)
3. exit game/exit steamcloud to sync files
P.S. only some files are synced (only specific files and some files with only certain extension .sav for example)
i don't know how to get info about what files are synced
I found out that i have another game with same feature and i managed to upload steam_api64.dll (renamed to steam-api64.sav)
I include here some screenshots
![before-web](https://github.com/user-attachments/assets/91ce6ecc-8a05-4722-8f31-5fb2c6ad6788)
![before-folder](https://github.com/user-attachments/assets/52c45695-1591-42c3-a9da-4c13e09b3611)
![after-folder](https://github.com/user-attachments/assets/f4a98d80-c047-434e-a272-0c0ff0e63b06)
![after-web](https://github.com/user-attachments/assets/4a06b2a6-19c3-44e8-86e7-f0bc0352ac71)

For that disconnect it seems that unload DLL doesn't helped. So i will let it be as is. Maybe i could add "Restart App" button or just exiting app works also.

**Comment by Wurrkop** [comment]
Ive tried the method of changing the files in the game folder while the game is running and then exiting, for my case it doesnt seem to work, i guess it could be some quirk to this specific game because if i try write protecting the known good local files  the game creates files called __writeback FILENAME in the local directory when running.

Ive also had files upload with the winappdatalocal tag/rootpath when i made extra files in the directory, initially i wasnt moving my backups out of the directory, just ctrl dragging them so when i looked at https://store.steampowered.com/account/remotestorageapp/?appid=2183900 i had a clutter of copies, removed those by cleaning up the folder during running the game, closing and having the sync take away what i removed, as i mentioned in my previous comment.

Essentially what i was trying to do with your app was to upload and replace the bad files in the cloud with my two good files, outside of the game, to try to circumvent whatever is holding on to the bad files in the cloud.

Had a read through the steam_auto-cloud link you posted, i dont understand much of it except that a "rootpath" option seems to what would be needed for my situation.

A way of "appending" the WinAppDataLocal rootpath/tag/property (or whatever the term should be) to the files/directories i manually upload through your app in order to replace the files in the cloud.

I realize this is likely to be quite niche so know that im very thankful that you are even looking at the issue :)

**Comment by rhsCZ** [comment]
Function used to write files to cloud only specify filename and what data to write. i think prefixing this to before filename could just error out or just upload to normal cloud. there isn't any other function that will help also.
In docs it's mentioned, that files are synced before playing and after exiting game so.
You could try edit your good file (add one character->save and delete it->save) or just make new file with copied contents to have newer date and time than that file on cloud. Replace file on that location and than hit Play. Maybe there should be pop up window from steam about outdated data on cloud asking if you want use files that you have locally or that ones already present on cloud.
Or delete all files in "C:\Users\USER\AppData\Local\Saber\Space Marine 2\storage\steam\user\USERID\Main\config\" while initialized in steamcloud (just enter appid and connect - don't worry about nothing showing up) and then exit app to let it sync. After that start steamcloud and connect again put those good files in, exit app and they should synchronize.
You don't need to run game just entering appid and connect button in steamcloud do the trick (avoid running game to prevent reading/writing and locking files while game is loading/running). This should kick in sync when you click connect and when you exit app.
I hope this will help you. Let me know how it went.

**Comment by Wurrkop** [comment]
I tried your suggest of add save/removing save a character to get the files to be most recent, uploading my files using the app, rather than pasting in behind the running game.
The files over on "view steam cloud" show as having been updated with the timestamp but it the game still retains the broken stuff somehow :/

Im starting to suspect my issue might actually be unrelated to steam cloud but rather related to the prismray.io cloud, i think its mirroring the files (as it has a functionality for save transfer between PC and consoles).
In addition to that, prismray could be running some sort of check to see if the files were created in online or offline mode.
(Offline mode play specifically notes that any progress will not carry over, the known good files i have were last written to by the game in offline mode.)

Im going to try unlinking steam from my prismray.io account and see if that sorts it because unless there is some other sorta oddness i really think steam ought to be picking up the files ive uploaded.

Will report back with further progress, or lack there of.

**Comment by rhsCZ** [comment]
I am sorry to hear that. Sadly i can't help you any more, but i tried at least. However i will leave it open for few days if you will have any more ideas to improve app.
